### ISSUE TITLE
Reverse proxy & paths

### ISSUE THREAD

**Issue by StefanoBalocco** [11cafe/comfyui-workspace-manager#355]
Hello,
I'm running comfyui behind a reverse proxy that maps mydomain/stablediffusion to ip:8188/

All works fine except for comfyui-workspace-manager.

In console I've saw that it tried to load /workspaces_web/filename instead of /stablediffusion/workspaces_web/filename.

Is an hardcoded path? Is possible to change it? Where I should touch?

**Comment by Weixuanf** [comment]
hi this is a known problem, see my comments about it: https://github.com/11cafe/comfyui-workspace-manager/issues/218#issuecomment-1988320957
it's not trivial to fix it, need to change lots of code. So I haven't found time to fix it yet. I'll try to prioritize it in future.

**Comment by StefanoBalocco** [comment]
Thank you, I didn't understood was the same problem.

Duplicate of #218

**Comment by StefanoBalocco** [comment]
Duplicate of #218

**Comment by Weixuanf** [comment]
hello this problem is fixed now in the latest version. You should be able to use workspace manager with proxies

**Comment by StefanoBalocco** [comment]
> hello this problem is fixed now in the latest version. You should be able to use workspace manager with proxies

Doesnt' work. In the console I still see that it tries to load /workspaces_web/filename instead of /stablediffusion/workspaces_web/filename.

**Comment by Weixuanf** [comment]
Can you screenshot your console log? Also your F12 Source tab would be helpful too
Thank you!

**Comment by Weixuanf** [comment]
F12 -> Sources tab should look like this:

<img width="423" alt="Screenshot 2024-06-20 at 12 33 22 AM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/d7799695-a2d9-4ddc-a622-f4b829e1f065">
